### ISSUE TITLE
dash-cli doesn't work in the dashpay container

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/mn-bootstrap#13]
**reproduce**
```
sudo docker exec -it <dashpay_container> /bin/bash
dash-cli help
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/dash/.dashcore/dash.conf)
```

**issue**
dash-cli doesn't work in the dashpay container
This may have been done for a reason but I don't understand why.

**suggested fix**
previous versions added following `volume` to dashpay container config in `docker-compose.yml`:
`./data/dash.conf:/root/.dashcore/dash.conf`

**Comment by strophy** [comment]
Workaround: `dash-cli -conf=/dashd.conf <command>`

This occurs because the dash.conf file is not mounted in the default location of `~/.dashcore/dash.conf`. Mounting it to `/dash/.dashcore/dash.conf` (or `/root/.dashcore/dash.conf`) is problematic because the directory does not exist in this location in the image, so bind mounting dash.conf there will create the directory with root owner, but dashd runs as user "dash" in the image and then cannot write the blockchain files to the data folder. The easiest way to fix this is modify the dashpay/dashd image.

**Comment by shumkov** [comment]
@strophy Are you sure it won't work?

**Comment by strophy** [comment]
Yes, I'm fairly sure. We can see it in one of my previous attempts [here](https://github.com/strophy/docker-masternode/blob/master/docker-compose.yml#L10).

This implementation bind-mounts `dash.conf` to `/dash/.dashcore/dash.conf` in the container. If the datadir is not manually specified (so dashd tries to use the default, i.e. `/dash/.dashcore/` then it will encounter the following error on start:

```
dashd       | 2020-03-24 07:36:50 Error: Cannot obtain a lock on data directory /dash/.dashcore. Dash Core is probably already running. No such file or directory.
dashd       | Error: Cannot obtain a lock on data directory /dash/.dashcore. Dash Core is probably already running. No such file or directory.
dashd exited with code 1
```

The `/dash/` directory has the following permissions:
`drwxr-xr-x 2 root root 4.0K Mar 24 07:32 .dashcore`

All other files in the folder have `dash/dash` user and group. If we want to use default locations for these files so `dash-cli` works without passing the `-conf` argument then the directory needs to be created in the docker image with the correct user. Other options are to use an alternative datadir location, and alternative conf file location, or run dashd as root in the container.

**Comment by strophy** [comment]
Discussion on this issue here: https://github.com/docker/compose/issues/3270

**Comment by shumkov** [comment]
The data dir specified outside home dir so it supposed to work properly https://github.com/dashevo/mn-bootstrap/blob/7f48d00db0d750705bae689b5f8c38b8554238f9/docker-compose.yml#L15

Actually, maybe better to move the data dir to `/dash/data`

**Comment by strophy** [comment]
Sure, that would work fine. The problems only occur if trying to keep both datadir and conf file in the default location, meaning the location dashd tries to put them if nothing is explicitly specified. This was my goal to keep the config as simple as possible and consistent with people using other installation methods, so that support is easier. But we can move the datadir as well, it isn't a big deal.

**Comment by shumkov** [comment]
We set `datadir` in command options so the setting from config will be overwritten. Should we close this issues?

**Comment by strophy** [comment]
Yes, let's close this. Resolution is to mount conf file in the default location where dash-cli expects it, and set `datadir` in the options.
